# Generated by Django 5.0.6 on 2024-05-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category1',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person1',
        ),
    ]
