# Generated by Django 5.0.6 on 2024-05-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person1', '0002_alter_category_table_alter_person_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
